//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCMD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperCMD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--For new line, type \n.--&gt;
        ///&lt;SuperCMD_Lang Name=&quot;en-US&quot; DispName=&quot;English&quot;&gt;
        ///	&lt;Common
        ///		BadOS=&quot;SuperCMD only runs on Windows Vista or newer operating system!&quot;
        ///		CantStartTI=&quot;&quot;
        ///		FileType_LNK=&quot;&quot;
        ///		CreateLnkOK=&quot;&quot;
        ///		CreateLnkOK_title=&quot;&quot;
        ///		CreateLnkFailed=&quot;&quot;
        ///		CreateLnkFailed_title=&quot;&quot;
        ///		StartingTI=&quot;&quot;
        ///		UseTIToken=&quot;&quot;
        ///	/&gt;
        ///	&lt;ContextMenuIntegration
        ///		RunAsSYSTEM=&quot;&quot;
        ///		RunAsSYSTEM_TI=&quot;&quot;
        ///	/&gt;
        ///&lt;/SuperCMD_Lang&gt;.
        /// </summary>
        internal static string defaultLanguage {
            get {
                return ResourceManager.GetString("defaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SuperCMD DPIaware=&quot;True&quot; W31UI=&quot;True&quot;&gt;
        ///  &lt;QLaunch&gt;
        ///    &lt;Q index=&quot;1&quot; name=&quot;Command Prompt&quot; exe=&quot;%windir%\System32\cmd.exe&quot; args=&quot;/k Title SuperCMD v2.0&quot; dir=&quot;C:\Users\Raymai\Desktop&quot; /&gt;
        ///    &lt;Q index=&quot;2&quot; name=&quot;Registry Editor&quot; exe=&quot;%windir%\regedit.exe&quot; /&gt;
        ///    &lt;Q index=&quot;3&quot; name=&quot;Task Manager&quot; exe=&quot;%windir%\System32\taskmgr.exe&quot; /&gt;
        ///    &lt;Q index=&quot;4&quot; name=&quot;Services&quot; exe=&quot;%windir%\System32\mmc.exe&quot; args=&quot;%windir%\System32\services.msc&quot; /&gt;
        ///    &lt;Q index=&quot;5&quot; /&gt;
        ///    &lt;Q  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultSettings {
            get {
                return ResourceManager.GetString("defaultSettings", resourceCulture);
            }
        }
    }
}
